#!/usr/bin/env bash
#Prints FizzBuzz, Fizz and Buzz
i=1
while [ $i -le 100 ]
do
    if [ $((i%15)) = 0 ]
    then
        echo "Fizzbuzz"
    elif [ $((i%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((i%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    (( i++ ))
done
