#!/usr/bin/env bash
#Prints Best school ten times with the 8th number as Good Luck and the fourth number as Bad luck
i=1
while [ $i -le 10 ]
do
    if [ $i == 4 ]
    then
        echo "bad luck"
    elif [ $i == 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( i++ ))
done
