#!/usr/bin/env bash
#Displays time for 12 hours and 59 minutes
h=0
while [ $h -le 12 ]
do
    echo "Hour: $h"
    i=1
    (( h++ ))
    while [ $i -le 59 ]
    do
        echo "$i"
        (( i++ ))
        
    done
    
done
